version: '3.4'

services:
  mssqllocaldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  spffront:
    image: spffront
    build:
      context: ./SimplePostsFeed/client
      dockerfile: Dockerfile
    depends_on:
      - spfback
  
  spfback:
    image: spfback
    build:
      context: .
      dockerfile: SimplePostsFeed/Dockerfile
    depends_on:
      - mssqllocaldb
